// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtsH3Am5vH8B7NYxQQEc8M2i_NvnYczxw',
    appId: '1:955137715469:web:17c17560ae929631d7d444',
    messagingSenderId: '955137715469',
    projectId: 'donymoyo-f1436',
    authDomain: 'donymoyo-f1436.firebaseapp.com',
    storageBucket: 'donymoyo-f1436.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0nf4EzGOSm--VYK_IRT5VCQNyaY2u_uc',
    appId: '1:955137715469:android:c3a762f6b54485d6d7d444',
    messagingSenderId: '955137715469',
    projectId: 'donymoyo-f1436',
    storageBucket: 'donymoyo-f1436.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJ7L9URPgAqcjJDntRDkf-zAhNbZMukuM',
    appId: '1:955137715469:ios:42f678e625d69733d7d444',
    messagingSenderId: '955137715469',
    projectId: 'donymoyo-f1436',
    storageBucket: 'donymoyo-f1436.firebasestorage.app',
    iosClientId: '955137715469-of7unvakhd036n7anl2men296nfqslpp.apps.googleusercontent.com',
    iosBundleId: 'com.example.donyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJ7L9URPgAqcjJDntRDkf-zAhNbZMukuM',
    appId: '1:955137715469:ios:42f678e625d69733d7d444',
    messagingSenderId: '955137715469',
    projectId: 'donymoyo-f1436',
    storageBucket: 'donymoyo-f1436.firebasestorage.app',
    iosClientId: '955137715469-of7unvakhd036n7anl2men296nfqslpp.apps.googleusercontent.com',
    iosBundleId: 'com.example.donyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtsH3Am5vH8B7NYxQQEc8M2i_NvnYczxw',
    appId: '1:955137715469:web:cb9b0c7e1a83c7b9d7d444',
    messagingSenderId: '955137715469',
    projectId: 'donymoyo-f1436',
    authDomain: 'donymoyo-f1436.firebaseapp.com',
    storageBucket: 'donymoyo-f1436.firebasestorage.app',
  );
}
